<?php

$textos = [

    //Vista de Index.php

    "titulo" => "Markets",
    "productos" => "Products",
    "contacto" => "Conctact",
    "nosotros" => "Us",
    "Introduccion-us" => "Chemical Broker started over 9 years ago, building on an even longer history of innovation and growth.",
    "distribuidor-us2" => "Today we have become one of the largest distributors of oleochemicals; fatty acids, fatty alcohols, glycerins, triglycerides, palm derivatives, fatty acid distillates, glycols, oils and fats, preservatives, among others",
    "distribuidor-us3" => "We see ourselves as the bridge connecting suppliers in distant locations with customers. And as a distribution channel, bringing essentials materials needed by thousan of manufacturers to create products that improve the lives of millions of costumer worlwide.",
    "distribuidor-us4" => "We are even expanding our product line as we develop bio-based renewable solutions for the future",
    "distribuidor-us5" => "And perhaps that´s truly what sets us apart. Because for everyone at Chemical Broker, it´s about more than just what we do; it´s about how we do it: a company guided by principles and driven by a passion to better server our suppliers and customers. every single day",
    "bussines-core1" => "Business Approach",
    "business-core2" => "Chemical Broker is a global provider of brokerage, marketing, distribution, import and export services for chemical ingredients. for the Pharmaceutical, Veterinary, Food & Human Nutrition, Food & Animal Nutrition, Agrochemicals, Cosmetics & Personal Care, Detergents & Household, and Chemical Industries",
    "Business" => "Business",
    "Business2" => "Our businesses provide services to the Pharmaceutical, Food and Human Nutrition, Cosmetics and Personal Care, Veterinary, Animal Feed and Nutrition, Agrochemical, Detergents and Home Care and Chemical Industries in general.",
    "Businness-Process" => "Business Process:",
    "Business-Map" => "Quality",
    "Business-Map2" => "Manufacturer",
    "Business-Map3" => "Supplier",
    "Business-Map4" => "Purchase",
    "Business-Map5" => "Chemical Ingredients",
    "Business-Map6" => "Sale",
    "Business-Map7" => "Chemical Ingredients",
    "Business-Map8" => "Consumer",
    "Business-Map9" => "Client",
    "Business-Map10" => "Quality Management System",
    "Business-Map11" => "<b><p>(Purchase | Chemical(s) Ingredients | Quality | Assurance | Logistic - Importar or Export | Assurance | Logistic | Quality | Chemical(s) Ingredient(s) | Sale)</p></b>",
    "Mission" => "<b>Mission</b>",
    "Mission2" => "The global sale and logistics of chemical ingredients",
    "Mission3" => "To be a global supplier of chemical ingredients that provides suitable and specific solutions in the acquisition of inputs for the chemical industry, focused on the needs of the client.",
    "Vision" => "Vision",
    "Vision2" => "To be the global leader in the marketing of chemical products, offering innovative, sustainable, and high-quality solutions that drive industrial and environmentally responsible development. Our commitment is to transform the chemical industry through operational excellence, strategic alliances, and a focus on customer satisfaction, promoting a positive impact in every market we serve.",


    //Vista de Historia y Hechos

    "Historiatitulo" => "Facts",
    "Historiaprimer-parrafo" => "Understanding the problems and difficulties faced daily by companies focused on the production of chemical ingredients and finished products around the world, due to inadequate and unprofessional supplier service in obtaining raw materials, as well as a lack of knowledge in matters of negotiation, acquisition, import, export, services and insurance coverage, the firm was created:",
    "Historiasegundo-parrafo" => "Chemical Broker, a company created in 2014, with a clear and defined business approach, described below:",
    "Historiatercer-parrafo" => "
    Facilitate – The buying and selling processes of chemical products to our business partners, through robust and long-term negotiations with the world's leading manufacturers and suppliers, allowing for greater profitability for Chemical Broker and our business partners.",
    "Historiacuarto-parrafo" => "Negotiate and Provide – Chemical products and services such as Services, International Trade (Imports and Exports) and Insurance Coverage for our business partners.",
    "Historiaquinto-parrafo" => "World-Class Quality – We only sell products and services of the highest quality, certified to the most demanding quality standards worldwide.",
    "Historiasexto-parrafo" => "Competitiveness. - By understanding the problems and difficulties of companies focused on the manufacture of chemical products and finished products, as well as companies focused on the distribution of chemical ingredients, we offer a Total Service, which aims to generate solutions suitable to the needs of our business partners in a timely manner.",
    "Historia2014-lineaTiempo" => "On July 10, 2014, the firm Chemical Broker was founded, focused on the sale of chemical ingredients for the Pharmaceutical, Food and Human Nutrition, Cosmetics and Personal Care and General Chemical Industries with the sale of Oleochemicals; Glycerins, Alcohols and Fatty Acids.",
    "Historia2015-lineaTiempo" => "
    New business opportunities are opening up with manufacturers worldwide for the sale of different Pharmaceutical Grade, USP, FCC and Cosmetic Grade products with a broad portfolio of products focused on the Pharmaceutical, Food and Human Nutrition and Cosmetics and Personal Care Divisions.",
    "Historia2016-lineaTiempo" => "New business opportunities are opening up with manufacturers worldwide for the sale of different Pharmaceutical Grade, USP, FCC and Cosmetic Grade products with a broad portfolio of products focused on the Pharmaceutical, Food and Human Nutrition and Cosmetics and Personal Care Divisions.",
    "Historia2017-lineaTiempo" => "Over the past decade, awareness of pet care and the quality of animal feed for human consumption has grown, driving companies to develop higher-quality food products. In response to this growing awareness, Chemical Broker created its Pet & Feed division, using the highest quality chemical ingredients, certified under Good Manufacturing Practices (GMP) for food grade, and specializing in the animal feed and nutrition industry.",
    "Historia2018-lineaTiempo" => "During 2018, Chemical Broker considered it important to develop its own Information Technology Business Unit, with the purpose of driving the digital age within the organization, to facilitate its services inside and outside of it.",


    //VALORES ORGANIZACIOANLES 

    "TITULO-VALORES" => "How We Govern Our Actions",
    "PARRAFO1-VALORES" => "Chemical Broker is an organization governed by universal values, applicable at all times and in all places, regardless of race, creed, economic status or any other type of distinction between living beings.",
    "PARRAFO2-VALORES" => "The universal values ​​we believe in strengthen relationships with our team and business partners and clearly describe the direction we want to take our organization.",
    "PARRAFO3-VALORES" => "Chemical Broker defines four values ​​as universal, which govern the actions of our organization",
    "TITULO-EXCELENCIA" => "Excellence",
    "DEFINICION" => "Definition",
    "DEFINICION-EXCELENCIA" => "Superior quality or goodness that makes a thing or a person worthy of appreciation and esteem.",
    "ETIMOLOGIA" => "Etymology",
    "ETIMOLOGIA-EXCELENCIA" => "The word excellence comes from the Latin, Excellentia-ae, from ex and cella, an Indo-European root *kel- in Greek kelo, meaning hidden or concealed place, cellar; from this derives the Spanish celda (cell) and in German keller (basement) and zelle (cell), due to the change in pronunciation of c as k in Classical Latin (keller) and c as ts in Ecclesiastical Latin (zelle). Excellentia would mean to come out of hiding, also signifying superiority, greatness, to rise, to be proud. From this word came brands such as, for example, the Excel computer program.",
    "EXCELENCIA-CHEMICALBROKER" => "Excellence for Chemical Broker",
    "EXCELENCIA-PARRAFO" => "Maximize the standards determined by Chemical Broker for each process:",
    "EXCELENCIA1" => "Quality Standard",
    "EXCELENCIA2" => "Quantity Standard",
    "EXCELENCIA3" => "Time Standard",
    "EXCELENCIA4" => "Cost Standard",
    "TITULO-SERVICIO" => "Service",
    "DEFINICION-SERVICIO" => "Action or set of activities aimed at satisfying a specific need of our business partners, providing an intangible and personalized product.",
    "ETIMOLOGIA-SERVICIO" => "It comes from the Latin servitium, composed of: the root of servitum. Supine of the verb servire (to attend to, to take care of, to serve, to be a slave, to adapt to another or to something else)",
    "ETIMOLOGIA-SERVICIO2" => "This word, in its etymology, comes from the Latin (servitium) which means servitude.",
    "SERVICIO-CHEMICALBROKER" => "Service for Chemical Broker",
    "SERVICIO-PARRAFO" => "We dedicate our efforts to the total satisfaction of our Business Partners.",
    "TITULO-COMPROMISO" => "Commitment",
    "DEFINICION-COMPROMISO" => "Formal agreement reached by two or more parties after making concessions between them",
    "ETIMOLOGIA-COMPROMISO" => "It comes from the Latin compromissum (an agreement to comply with the award of an arbitrator)",
    "COMPROMISO-CHEMICALBROKER" => "To provide our business partners with a comprehensive and exclusive service for their complete satisfaction.",
    "TITULO-ETICA-EMPRESARIAL" => "Business Ethics",
    "DEFINICION-ETICA-EMPRESARIAL" => "Business ethics is a branch of applied ethics. It deals with the study of normative questions of a moral nature that arise in the business world.",
    "ETIMOLOGIA-ETICA-EMPRESARIAL" => "It is found in Latin as ethĭca, the feminine form of ethĭcus, which originates from the Greek ēthikḗ, the feminine form of ēthikós. It is used to refer to the study of human actions aimed at achieving good; it is the will to act correctly.",
    "ETICA-EMPRESARIAL-CHEMICALBROKER" => "Acting with respect, transparency, and strict compliance with our commitments to our business partners; members of the organization, society, government, clients, and suppliers, adhering to the current legal framework between Chemical Broker and those involved.",

    //SERVICIO INTEGRAL

    "SERVICIO-INTEGRAL" => "Chemical Broker distinguishes itself through excellence in its global business, by providing a 'Comprehensive Service' to our business partners in the sale of chemical products, based on the following principles:",
    "SERVICIO-INTEGRAL-LISTA" => "<ol><li>World Quality</li><li>Timely Supply</li><li>Warranty</li><li>Security</li><li>Fair and Competitive Prices</li><li>Personalized attention; pre, during, and post-sales</li></ol>",
    "EN-CHEMICALBROKER" => "In Chemical Broker",
    "TITULO-CALIDAD-MUNDIAL" => "The products we offer to our customers comply with international standards for Quality, Safety and Good Manufacturing Practices (GMPs), which can be consulted on the following page: Global Quality Standards",
    "SUBTITULO-ABASTECIMIENTO" => "There is no product more expensive than the one you don't have.",
    "PARRAFO-ABASTECIMIENTO" => "We work with quarterly, semi-annual, and annual consumption forecasts with our business partners; this guarantees the quantity of product requested and allows us to meet their requirements on time and in the proper manner.",
    "PARRAFO2-ABASTECIMIENTO" => "We have Distribution Centers in compliance with Good Manufacturing Practices (GMPs) and certified in the International Standards ISO 9001 & FSSC 22,000, in the main cities of Mexico, with a storage capacity of 30 calendar days, for the scheduled consumption of our business partners.",
    "PARRAFO3-ABASTECIMIENTO" => "Our Logistics is certified under the international standards ISO 90001 & FSCC 22,000, in compliance with the highest standards of sanitation, safety and time.",
    "TITULO-GARANTIAPROD" => "Product Warranty",
    "PARRAFO-GARANTIA-PROD" => "We guarantee the complete satisfaction of our business partners, with products in optimal condition in terms of quality (world-class quality), shelf life, compliance with specifications, correct packaging, compliance with previously requested characteristics, and priority attention to any non-conformity that may arise.",
    "TITULO-SEGURIDAD-PRODUCTO" => "Product Safety",
    "Parrafor-Garantia-Producto" => "We offer risk coverage to cover any incident that may occur during the purchase and sale transaction.",
    "TITULO-PRECIOS-JUSTOS" => "Fair and Competitive Prices",
    "PARRAFO-PRECIOS-JUSTOS" => "The value of our chemical products is defined according to the following categories:",
    "LISTA-PRECIOS-JUSTOS" => "<li>Quality</li><li>Certifications</li><li>Market value</li>",
    "ATENCION-PERSONAL-TITULO" => "Personalized attention before, during and after the sale",
    "PARRAFO-ATENCION-PERSONAL" => "Our organization is made up of specialized members, in each of the job positions where they develop their strategic and operational skills.",
    "PARRAFO-ATENCION-PERSONAL2" => "Chemical Broker's Sales Executives are specialists in the chemical industry for each of the divisions we serve (for example: Food Engineers, Chemical Engineers, Pharmaceutical Chemists, etc.).",
    "PARRAFO-ATENCION-PERSONAL3" => "Our sales process is standardized according to the International Standard ISO 9001, to reduce omissions, errors or lack of efficient service.",
    "PARRAFOR-ATENCION-PERSONAL4" => "The sale of our chemical products is carried out with personalized attention to know, understand and satisfy the needs of our customers",
    
];