<?php

$textos = [

    //Vista de Index.php

    "titulo" => "Mercados",
    "productos" => "Productos",
    "contacto" => "Contacto",
    "nosotros" => "Nosotros",
    "Introduccion-us" => "<b style='color:#071637'>Chemical Broker</b> comenzó hace más de 9 años, nos basamos en una historia aún más larga de innovación y crecimiento.",
    "distribuidor-us2" => "Hoy nos hemos convertido en uno de los mayores distribuidores de Oleo químicos; Ácidos Grasos, Alcoholes Grasos, Glicerinas, Triglicéridos, Derivados de Palma, Destilados de Ácidos Grasos, Glicoles, Aceites y Grasas, Conservadores, entre otros.",
    "distribuidor-us3" => "Nos vemos a nosotros mismos como el puente que conecta a los proveedores en lugares lejanos con los clientes. Y como un canal de distribución, que trae materiales esenciales, necesarios para miles de fabricantes, para crear productos que mejoren la vida de millones de consumidores en todo el mundo.",
    "distribuidor-us4" => "Incluso estamos ampliando nuestra línea de productos mientras desarrollamos soluciones renovables de base biológica para el futuro.",
    "distribuidor-us5" => "Y tal vez eso es realmente lo que nos diferencia. Porque para todos en Chemical Broker, se trata de más que simplemente lo que hacemos, se trata de la forma en como lo hacemos: una empresa, guiada por principios e impulsada por la pasión de servir mejor a nuestros proveedores y clientes, todos los días.",
    "bussines-core1" => "Enfoque de Negocios",
    "business-core2" => "Chemical Broker es un proveedor mundial de servicios de intermediación, comercialización, distribución, importación y exportación de ingredientes químicos, para las industrias de Farmaceutica, Veterinaria, Alimentaria & Nutricion humana , Alimentaria & Nutricion animal, Agroquímicos, Cosmeticos & Cuidado Perosnal, Detergentes & Hogar, Químicos.",
    "Business" => "Negocios",
    "Business2" => "Nuestros negocios brindan servicio a la Industrias Farmacéutica, Alimentaria y Nutrición Humana, Cosmética y del Cuidado Personal, Veterinaria, Alimento y Nutrición Animal, Agroquímicos, Detergentes y Cuidado del Hogar y la Industria Química en general.",
    "Businness-Process" => "Proceso de Negocios:",
    "Business-Map" => "Calidad",
    "Business-Map2" => "Fabricante",
    "Business-Map3" => "(Proveedor)",
    "Business-Map4" => "Compra",
    "Business-Map5" => "Ingredientes QuÍmicos",
    "Business-Map6" => "Venta",
    "Business-Map7" => "Ingredientes QuÍmicos",
    "Business-Map8" => "Consumidor",
    "Business-Map9" => "(Cliente)",
    "Business-Map10" => "Sistema de Gestión Integral",
    "Business-Map11" => "<b><p>(Compra | Ingrediente(s) Químico(s) | Calidad | Aseguramiento | Logística - Importación o Exportación | Aseguramiento | Logística | Calidad | Ingrediente(s) Químico(s) | Venta)</p></b>",
    "Mission" => "Misión",
    "Mission2" => "La venta y logística global de ingredientes químicos",
    "Mission3" => "Ser un proveedor mundial de ingredientes químicos que aporte soluciones adecuadas y especificas en la adquisición de insumos para la industria química, enfocados en las necesidades del cliente.",
    "Vision" => "Visión",
    "Vision2" => "Ser el líder global en la comercialización de productos químicos, ofreciendo soluciones innovadoras, sostenibles y de alta calidad que impulsen el desarrollo industrial y ambientalmente responsable. nuestro compromiso es transformar la industria química a través de excelencia operativa, alianzas estratégicas y un enfoque en la satisfacción de nuestros clientes, promoviendo un impacto positivo en cada mercado que atendemos.",

    //Vista de Historia y Hechos

    "Historiatitulo" => "Hechos",
    "Historiaprimer-parrafo" => "Al entender los problemas y dificultades que viven diariamente las empresas enfocadas en la producción de ingredientes químicos y productos terminados alrededor del mundo, por la obtención de materias primas debido a un servicio inadecuado y poco profesional de proveedores, así como por desconocimiento en temas de negociación, adquisición, importación, exportación, Servicios y coberturas de seguros, se crea la firma:",
    "Historiasegundo-parrafo" => "Chemical Broker , una compañía creada en el año 2014, con un enfoque de negocios claro y definido, descrito a continuación:",
    "Historiatercer-parrafo" => "Facilitar . – Los procesos de compra y venta de productos químicos a nuestros socios de negocios, por medio de negociaciones robustas y de largo plazo con los principales fabricantes y proveedores en el mundo permitiendo crear una mayor rentabilidad para Chemical Broker y nuestros socios de negocios.",
    "Historiacuarto-parrafo" => "Negociar y Proveer . – Productos químicos y servicios como Servicios, Comercio Internacional (Importaciones y Exportaciones) y Coberturas de Seguros para nuestros socios de negocios.",
    "Historiaquinto-parrafo" => "Calidad Mundial – Solo vendemos productos y servicios de la más alta calidad certificados en las normas de calidad más exigentes a nivel mundial.",
    "Historiasexto-parrafo" => "Competitividad. - al entender los problemas y dificultades de las empresas enfocadas en la fabricación de productos químicos y productos terminados, así como de las empresas enfocadas en la distribución de ingredientes químicos, ofrecemos un Servicio Total, el cual tiene como objetivo generar soluciones adecuadas a las necesidades de nuestros socios de negocios en tiempo y forma.",
    "Historia2014-lineaTiempo" => "El 10 de Julio de 2014 se funda la firma Chemical Broker enfocada en la venta de ingredientes químicos para las Industrias de Farmacéutica, Alimentos y Nutrición Humana, Cosméticos y Cuidado Personal y la Industria Química general con la venta de Oleo químicos; Glicerinas, Alcoholes y Ácidos Grasos.",
    "Historia2015-lineaTiempo" => "Se abren nuevas oportunidades de negocio con fabricantes a nivel mundial para la venta de diferentes productos Grado Farmacéutico, USP, FCC y Grado Cosmético con un amplio portafolio de productos enfocado a las Divisiones Farmacéutica, Alimento y Nutrición Humana y Cosméticos y Cuidado Personal.",
    "Historia2016-lineaTiempo" => "Se amplía nuestro enfoque de negocios con la venta de Ingredientes Químicos para la División de Agroquímicos, con un portafolio de productos enfocado a atender a los fabricantes de Reguladores de Crecimiento, Pesticidas y Fertilizantes, así como a empresas comercializadoras de materias primas para la industria de Agroquímicos.",
    "Historia2017-lineaTiempo" => "En la última década la concientización sobre el cuidado de los animales de compañía, así como el tipo de alimentación de los animales para consumo humano ha crecido impulsando a las empresas a generar productos alimenticios de mejor calidad. Bajo las circunstancias del momento Chemical Broker crea su división de Pet & Feed con ingredientes químicos de la más alta calidad, certificados en Buenas Prácticas de Manufactura Grado Alimentos y con un enfoque especializado en la Industria de Alimentación y Nutrición Animal.",
    "Historia2018-lineaTiempo" => "Durante el año 2018 Chemical Broker considera importante desarrollar su propia Unidad de Negocios de Tecnologías de la Información, con el propósito de impulsar la era digital dentro de la organización, para facilitar sus servicios dentro y fuera de ella",


    //VALORES ORGANIZACIOANLES 

    "TITULO-VALORES" => "Como Regimos Nuestro Actuar",
    "PARRAFO1-VALORES" => "Chemical Broker es una organización regida por valores universales, aplicables en todo momento y lugar, sin importar raza, credo, posición económica o cualquier otro tipo de distinción entre seres vivos.",
    "PARRAFO2-VALORES" => "Los valores universales en los que creemos fortalecen las relaciones con nuestro  equipo de trabajo y nuestros socios de negocios y describen claramente en que dirección queremos llevar nuestra organización.",
    "PARRAFO3-VALORES" => "Chemical Broker define 4 valores como universales, los cuales rigen el actuar de nuestra organización",
    "TITULO-EXCELENCIA" => "Excelencia",
    "DEFINICION" => "Definición",
    "DEFINICION-EXCELENCIA" => "Superior calidad o bondad que hace digna de aprecio y estima una cosa o a una persona.",
    "ETIMOLOGIA" => "Etimología",
    "ETIMOLOGIA-EXCELENCIA" => "La palabra excelencia viene del latín, Excellentia-ae, de ex y cella una raíz indoeuropea *kel- en griego kelo que significa lugar oculto o escondido, bodega, de ahí derivo la castellana celda y en alemán keller (sótano) y zelle (celda), por el cambio de la pronunciación de c como k en el latin clásico (keller) y la c como ts en el eclesiastico (zelle). excellentia, significaría salir de lo oculto, significando también superioridad, grandeza, elevarse, enorgullecerse, De esta palabra, salieron marcas como, por ejemplo. El programa para computadoras Excel.",
    "EXCELENCIA-CHEMICALBROKER" => "arrow_forward_iosExcelencia para Chemical Broker",
    "EXCELENCIA-PARRAFO" => "Maximizar los Estándares determinados por Chemical Broker para cada proceso:",
    "EXCELENCIA1" => "Estándar de Calidad",
    "EXCELENCIA2" => "Estándar de Cantidad",
    "EXCELENCIA3" => "Estándar de Tiempo",
    "EXCELENCIA4" => "Estándar de Costo",
    "TITULO-SERVICIO" => "Servicio",
    "DEFINICION-SERVICIO" => "Acción o conjunto de actividades destinadas a satisfacer una determinada necesidad de nuestros socios de negocios, brindando un producto inmaterial y personalizado.",
    "ETIMOLOGIA-SERVICIO" => "Viene del latín servitium compuesto con: la raíz de servitum. Supino del verbo servire (atender, cuidar, servir, ser esclavo, adaptarse a otro o a otra cosa)",
    "ETIMOLOGIA-SERVICIO2" => "Este vocablo en su etimología procede del latín (servitium) que quiere decir servidumbre.",
    "SERVICIO-CHEMICALBROKER" => "arrow_forward_iosServicio para Chemical Broker",
    "SERVICIO-PARRAFO" => "Dedicamos nuestros esfuerzos a la satisfacción total de Nuestros Socios de Negocios.",
    "TITULO-COMPROMISO" => "Compromiso",
    "DEFINICION-COMPROMISO" => "Acuerdo formal al que llegan dos o más partes tras hacer concesiones entre ellas",
    "ETIMOLOGIA-COMPROMISO" => "Viene del latín compromissum (un acuerdo para cumplir con la adjudicación de un árbitro)",
    "COMPROMISO-CHEMICALBROKER" => "Brindar a nuestros socios de negocios un Servicio Integral y exclusivo para su completa satisfacción.",
    "TITULO-ETICA-EMPRESARIAL" => "Etica Empresarial",
    "DEFINICION-ETICA-EMPRESARIAL" => "La ética empresarial es una rama de la ética aplicada. Se ocupa del estudio de las cuestiones normativas de naturaleza moral que se plantean en el mundo de los negocios.",
    "ETIMOLOGIA-ETICA-EMPRESARIAL" => "Se ubica en el latín como ethĭca, forma femenina de ethĭcus, cuyo origen se distingue en el griego ēthikḗ, en calidad de femenino de ēthikós. Es utilizada para referirse al estudio de los actos humanos con el fin de alcanzar el bien, es la voluntad de actuar de manera correcta.",
    "ETICA-EMPRESARIAL-CHEMICALBROKER" => "Actuar con Respeto, Transparencia y Cumplimiento estricto a nuestros compromisos con Nuestros Socios de Negocios; miembros de la organización, sociedad, gobierno, clientes y proveedores, apegado al marco legal vigente entre Chemical Broker y los involucrados.",
    
    //PREMISAS ORGANIZACIONALES

    "PREMISAS-TITULO" => "Premisas",
    "PREMISAS-PARRAFO" => "Las Premisas para Chemical Broker son el núcleo de nuestro pensamiento organizacional, permitiéndonos actuar de igual forma con nuestros socios de negocios, así como mejorar constantemente nuestros procesos productivos y de negocios.",
    "PREMISAS-PARRAFO2" => "Chemical Broker basa su actuar en 3 premisas morales o bases fundamentales, las cuales establecen la directriz a seguir para nuestra Organización.",
    "ORDEN-DEFINICION" => "Definición",
    "ORDEN-PARRAFO" => "Es la manera de estar colocadas las cosas en el espacio o de sucederse los hechos en el tiempo, según un determinado criterio o una determinada norma y de acuerdo con un plan, el cual se contrapone a la casualidad y el caos.",
    "ORDEN-ETIMOLOGIA" => "Etimología",
    "ETIMOLOGIA-ORDEN" => "Es una palabra originaria del latín 'ordin' de la cual derivan muchas otras palabras como ordenar, ordenado, ordenamiento, ordenador entre muchas otras, esta palabra latina viene de una raíz indoeuropea 'ar'  que significa mover o ajustar.",
    "ORDEN-CHEMICALBROKER" => "Orden para Chemical Broker",
    "ORDEN-CHEMICALBROKER" => "Organizar el espacio de trabajo de forma eficaz. Al aplicarlo en la vida diaria, mejora los resultados.",
    "TITULO-SEGURIDAD" => "Seguridad",
    "DEFINICION-SEGURIDAD" => "Es la ausencia de peligro o riesgo. En términos generales, la seguridad se define como 'el estado de bienestar que percibe y disfruta el ser humano'. Según la pirámide de Maslow, la seguridad en el ser humano ocupa el segundo nivel dentro de las necesidades de déficit. Según la teoría de las necesidades de Bronisław Malinowski, la seguridad es una de las siete necesidades básicas a satisfacer por el ser humano.",
    "DEFINICION-SEGURIDAD2" => "la seguridad tiene como objetivo la prevención de riesgos en todos y cada uno de sus procesos productivos y de negocios.",
    "ETIMOLOGIA-SEGURIDAD" => "Proviene del latín “securitas”, que a su vez deriva de “securus”(sin cuidado, sin precaución, sin temor a preocuparse), que significa libre de cualquier peligro o daño.",
    "SEGURIDAD-CHEMICALBROKER-TITULO" => "Seguridad para Chemical Broker",
    "SEGURIDAD-CHEMICALBROKER" => "es la ausencia de riesgo y el estado de bienestar que el ser humano percibe y disfruta en su vida diaria.",
    "TITULO-LIMPIEZA" => "Limpieza",
    "DEFINICION-LIMPIEZA" => "Es la acción de limpiar la suciedad, lo superfluo o lo perjudicial de algo. Es la precisión con que se ejecuta algo y a la integridad de una organización en todo momento y circunstancia dentro y fuera del ámbito de negocios.",
    "ETIMOLOGIA-LIMPIEZA" => "La palabra limpieza, deriva de la palabra  “limpio”  (cualidad de no tener suciedad) y el sufijo: “-eza”.Limpio, deriva del latín “limpidus” , que se refiere a algo “claro” o “sin manchas”.",
    "TITULO DE LIMPIEZA" => "Limpieza para Chemical Broker",
    "LIMPIEZA-CHEMICALBROKER" => "es la pulcritud en la manera de ejecutar tus acciones diarias que te haga sentir satisfecho.",


    //SERVICIO_INTEGRAL

    "SERVICIO-INTEGRAL" => "Chemical Broker se distingue por la excelencia en sus negocios a nivel global, por medio de un “Servicio Integral” dirigido a nuestros socios de negocios, en la Venta de Productos Químicos, al considerar los siguientes fundamentos:",
    "SERVICIO-INTEGRAL-LISTA" => "<ol><li>Calidad Mundial</li><li>Abastecimiento Oportuno</li><li>Garantia</li><li>Seguridad</li><li>Precios Justos y Competitivos</li><li>Atencion Personal; pre,inter, post venta</li></ol>",
    "EN-CHEMICALBROKER" => "En Chemical Broker",
    "TITULO-CALIDAD-MUNDIAL" => "Los productos que ofrecemos a nuestros clientes cumplen, con las normas internacionales de Calidad, Inocuidad y Buenas Prácticas de Manufactura (BPM´s), las cuales podrán consultarse en la siguiente página Normas de Calidad Mundial",
    "SUBTITULO-ABASTECIMIENTO" => "No hay producto más caro, que aquel que No se tiene",
    "PARRAFO-ABASTECIMIENTO" => "Trabajamos con pronósticos de consumos trimestrales, semestrales y anuales con nuestros socios de negocios; lo cual garantiza la cantidad de producto solicitado y permite cumplir en tiempo y forma con sus requerimientos.",
    "PARRAFO2-ABASTECIMIENTO" => "Contamos con Centros de Distribución en cumplimiento con Buenas Prácticas de Manufactura (BMP´s) y Certificados en las Normas Internacionales  ISO 9001 & FSSC 22,000, en las principales Ciudad de México, con una capacidad de almacenamiento de 30 días naturales, para el consumo programado de nuestros socios de negocios.",
    "PARRAFO3-ABASTECIMIENTO" => "Nuestra Logística está certificada en las normas internacionales ISO 90001 & FSCC 22,000, en cumplimiento con los máximos estándares de sanitización, inocuidad y tiempo.",
    "TITULO-GARANTIAPROD" => "Garantia del Producto",
    "PARRAFO-GARANTIA-PROD" => "Garantizamos la entera satisfacción de nuestros socios de negocios, con productos en óptimas condiciones de calidad (calidad mundial), vida de anaquel, cumplimento a especificaciones, correcto empaque, cumplimento a características solicitadas previamente y atención prioritaria ante cualquier no conformidad que pudiera presentarse.",
    "TITULO-SEGURIDAD-PRODUCTO" => "Seguridad del Producto",
    "Parrafor-Garantia-Producto" => "Ofrecemos coberturas de riesgo para cubrir cualquier incidente, que pudiera suscitarse durante la operación de compra – venta.",
    "TITULO-PRECIOS-JUSTOS" => "Precios Justos y Competitivos",
    "PARRAFO-PRECIOS-JUSTOS" => "El valor de nuestros productos químicos es definido acorde a los siguientes rubros:",
    "LISTA-PRECIOS-JUSTOS" => "<li>Calidad</li><li>Certificaciones</li><li>Valor de mercado</li>",
    "ATENCION-PERSONAL-TITULO" => "Atencion Personal Pre, Inter y Post-Venta",
    "PARRAFO-ATENCION-PERSONAL" => "Nuestra organización está formada por miembros especializados, en cada uno de los puestos de trabajo donde desarrollan sus habilidades estratégicas y operativas.",
    "PARRAFO-ATENCION-PERSONAL2" => "Los Ejecutivos de Ventas de Chemical Broker son personas especializadas en la industria química para cada una de las divisiones que atendemos, (por ejemplo: Ingenieros en Alimentos, Ingenieros Químicos, Químicos Farmacobiólogo, etc.).",
    "PARRAFO-ATENCION-PERSONAL3" => "Nuestro proceso de ventas es estandarizado acorde a la Norma Internacional ISO 9001, para reducir las omisiones, errores o falta de un servicio eficiente.",
    "PARRAFOR-ATENCION-PERSONAL4" => "La venta de nuestros productos químicos se realiza con una atención personalizada para conocer, entender y satisfacer las necesidades de nuestros clientes",


    //CODIGO DE CONDUCTA

    "TITULO_CODIGO_CONDUCTA" => "Codigo de Conducta",
    "PRIMER_PARRAFO_COFC" => "El Código Global de Ética refleja nuestra filosofía corporativa, definiendo nuestros valores básicos y los estándares de conducta que se esperan de los integrantes de Chemical Broker, interna y externamente, El Código Global de Ética establece los principios para el trato justo y respetuoso de nuestros colaboradores y socios de negocios.",
    "PRIMER_SUBTITULO_COFC" => "Compromiso de Responsabilidad Corporativa de Chemical Broker",
    "SEGUNDO_PARRAFO_COFC" => "Chemical Broker combino el éxito económico y la responsabilidad social, con la protección del medio ambiente. Y esto lo llevamos a cabo como una Organización. Por tanto, nuestra normativa de responsabilidad corporativa es fundamentalmente la misma a nivel nacional e internacional y está basada en un Código de Conducta.",
    "TERCER_PARRAFO_COFC" => "Para tener éxito en lo que hacemos y para poner en práctica nuestra estrategia  “Nuestra excelencia, está en nuestro Servicio”, es vital que todos y cada uno de los integrantes del equipo de Chemical Broker conozcan y apliquen nuestros valores: Excelencia, Servicio, Compromiso y Ética Empresarial.",
    "SEGUNDO_SUBTITULO_COFC" => "Nuestro valor 'Compromiso' refleja nuestra adhesión completa al compromiso de responsabilidad corporativa",
    "TERCER_SUBTITULO_COFC" => "¿Qué quiere decir esto?",
    "CUARTO_PARRAFO_COFC" => "No hay nada más importante que nuestra integridad tanto empresarial como individual Chemical Broker está estrictamente comprometido con el riguroso cumplimiento de la ley, así como con una ética empresarial, y espera que todos los empleados se adhieran a dichas normas. Dicho compromiso debe desarrollarse plenamente en la organización, dado que cada uno de los individuos actúa como embajador de la empresa. Para nosotros, es de vital importancia que su comportamiento sea conforme a nuestras normas; estas no se pueden ver comprometidas.",
    "QUINTO_PARRAFO_COFC" => "Estamos convencidos de que nuestro sistema de cumplimiento, que ha estado mejorando de forma continua se viene desarrollando desde su introducción, ha demostrado ser eficaz. No obstante, su cumplimiento siempre constituirá un reto y debemos fomentar y seguir desarrollando de forma permanente nuestra cultura de cumplimiento en función de nuestros valores.",
    "SEXTO_PARRAFO_COFC" => "Por tanto, esperamos que asuma la responsabilidad personal de cumplir con todas:",
    "LISTA1_COFC" => "<li>Las leyes aplicables,</li><li>Los estándares internacionales básicos,</li><li>Las políticas y directivas corporativas.</li>",
    "SEPTIMO_PARRAFO_COFC" => "El Código de Conducta Chemical Broker, resume leyes importantes y políticas corporativas que regulan el comportamiento de todos los individuos de nuestra organización; en sus tratos con socios comerciales, responsables, otros individuos y la sociedad. Aunque nos orienta para que tomemos las decisiones correctas, no cubre todas las situaciones a las que nos enfrentamos. Es posible que sean de aplicación leyes y normativas específicas en determinados campos de actividad o ubicaciones.",
    "OCTAVO_PARRAFO_COFC" => "Garantizar el cumplimiento forma parte de nuestro trabajo diario. Los integrantes del equipo de Chemical Broker debemos mantener y seguir desarrollando una verdadera cultura en la que los ejecutivos actúen como modelos de referencia a la hora de promover la ética empresarial y el cumplimiento legal, y en la que el cumplimiento sea responsabilidad de todos.",
    "NOVENO_PARRAFO_COFC" => "Chemical Broker tiene el compromiso de proporcionarle toda la información y la asistencia que precisa para cumplir con estas obligaciones. En caso de duda, solo tiene que preguntar.",
    "TEXTO_FINAL_COFC" => "Gracias por su compromiso.",
    "TEXTO_FINAL_COFC" => "Nuestro Código Global de Ética se encuentra disponible en archivo PDF, en Español.",
    "COFC_BOTON_DESCARGA" => "Descargar Codigo de Conducta",

    //POLITICA DE CALIDAD 

    "TITULO_POLITICA_CALIDAD" => "Política de Calidad",
    "PRIMER_PARRAFO_POLITICA_CALIDAD" => "Para Chemical Broker nuestro compromiso es lograr la satisfacción de las necesidades de nuestros socios de negocios y su desarrollo a través de la comercialización de ingredientes químicos, para las industrias: Farmacéutica, Nutrición Humana, Veterinaria, Nutrición Animal, Cosmética & Cuidado Personal, Agroquímicos, Detergentes, Cuidado del Hogar e Industria Química en general, para cumplir con el marco regulatorio, normas y políticas aplicables, con el principal objetivo de lograr la mejora continua de nuestros procesos y nuestro Sistema de Gestión Integral.",
    "TITULO_OBJETIVOS_CALIDAD" => "Objetivos de Calidad",
    "LISTA_OBJETIVOS_CALIDAD" => "<li>Mantener la satisfacción del Cliente.</li><li>Mantener la rentabilidad del negocio.</li><li>Crecimiento en ventas anuales.</li><li>Mejorar continuamente el resultado de nuestros procesos de nuestro Sistema de Gestión Integral.</li><li>Promover el desarrollo personal y profesional de los miembros de la Organización.</li><li>Mejora continua del Sistema de Gestión Integrado.</li><li>Cumplir con el marco legal regulatorio; normas y políticas aplicables.</li>",

    //MERCADOS

    "TITULO_MERCADOS" => "Chemical Broker es un proveedor mundial de servicios de intermediación, comercialización, distribución, importación y exportación de ingredientes químicos, para las industrias Farmacéutica, Veterinaria, Alimentaria y Nutrición Humana, Nutrición Animal, Cosmética y del Cuidado Personal, Detergentes, Agroquímica, Industrial e Industria Química en general.",
    "TITULO_FARMACEUTICA" => "Farmacéutica",
    "TEXTO_FARMACEUTICA" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "BOTON_LEER_MAS" => "Leer Más",
    "TITULO_VETERINARIA" => "Veterinaria",
    "TEXTO_VETERINARIA" => "Soluciones nutricionales y productos para la industria veterinaria.",
    "TITULO_ALIMENTARIA" => "Alimentaria & Nutrición Humana",
    "TEXTO_ALIMENTARIA" => "Ingredientes y soluciones para la industria alimentaria y de nutrición.",
    "TITULO_NUTRICION_ANIMAL" => "Nutrición Animal",
    "TEXTO_NUTRICION_ANIMAL" => "Ingredientes y soluciones para mejorar el rendimiento y salud animal.",
    "TITULO_AGROQUIMICOS" => "Agroquímicos",
    "TEXTO_AGROQUIMICOS" => "Soluciones químicas para la protección y optimización de cultivos.",
    "TITULO_COSMETICOS" => "Cosméticos & Cuidado Personal",
    "TEXTO_COSMETICOS" => "Ingredientes especializados para formulaciones de belleza y cuidado personal.",
    "TITULO_DETERGENTES" => "Detergentes",
    "TEXTO_DETERGENTES" => "Materias primas y soluciones para productos de limpieza y mantenimiento.",
    "TITULO_QUIMICA_INDUSTRIAL" => "Química Industrial",
    "TEXTO_QUIMICA_INDUSTRIAL" => "Suministro de materias primas y soluciones para procesos industriales.",


    //INDUSTRIA FARMACEUTICA

    "SLOGAN_FARMACEUTICA" => "“Calidad en cada ingrediente; Nuestro compromiso con la excelencia farmacéutica”",
    "PRIMER_PARRAFO_FARMACEUTICA" => "La Industria Farmacéutica provee al mundo soluciones que permiten preservar la salud humana y mejorar su calidad de vida.",
    "SEGUNDO_PARRAFO_FARMACEUTICA" => "Chemical Broker ofrece un amplio portafolio de excipientes que cumplen con las Farmacopeas Internacionales y las Buenas Prácticas de Manufactura ICH-Q7. Nos consolidamos como uno de los principales proveedores a nivel global y líderes en México en la comercialización de este tipo de ingredientes químicos, garantizando calidad, trazabilidad, cumplimiento regulatorio y un suministro confiable para la industria farmacéutica.",
    "PRIMER_SUBTITULO_FARMACEUTICA" => "Excipientes",
    "TERCER_PARRAFO_FARMACEUTICA" => "En la fabricación de medicamentos para una mejor calidad de vida, los Excipientes, son las sustancias responsables de que los Activos cumplan con su cometido al ser mezclados entre sí y pueden constituir el 90% de la composición total de un medicamento:",
    "BANNERS_FARMACEUTICA" => "Los excipientes funcionan como vehículo para darle cuerpo, textura, forma y conservación al principio activo, facilitando su ingesta y regulando su actividad en el organismo.",
    "SEGUNDO_SUBTITULO_FUNCIONES" => "Funciones",
    "LISTA_FUNCIONES" => "<li>Aumentan el valor de la fórmula, pues las cantidades de Principio Activo (API´S) por sus siglas en inglés, por dosis, a veces son sumamente pequeñas.</li><li>Aseguran la estabilidad del Principio Activo, como lubrificantes, espesantes, deshidratantes y aglutinantes.</li><li>Mejoran las propiedades organolépticas; es decir el sabor, el olor y la apariencia del fármaco como colorantes, edulcorantes, aromatizantes.</li><li>Mejoran la biodisponibilidad; es decir la cantidad de fármaco que llega al torrente sanguíneo.</li>",
    "TITULO_SPRAYS_NASALES" => "Sprays Nasales",
    "TEXTO_SPRAY_NASAL" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "TITULO_JARABES" => "Jarabes",
    "TEXTO_JARABES" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "TITULO_POMADAS" => "Pomadas y Ungüentos",
    "TEXTO_POMADAS" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "TITULO_TABLETAS_DURAS" => "Tabletas Duras",
    "TEXTO_TABLETAS_DURAS" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "TITULO_CAPSULAS_BLANDAS" => "Capsulas Blandas",
    "TEXTO_CAPSULAS_BLANDAS" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "TITULO_SUPOSITORIOS" => "Supositorios",
    "TEXTO_SUPOSITORIOS" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "TITULO_INYECTABLES" => "Injectables",
    "TEXTO_INYECTABLES" => "Ingredientes y soluciones para la industria Farmacéutica.",
    "TITULO_SUPLEMENTOS" => "Suplementos",
    "TEXTO_SUPLEMENTOS" => "Ingredientes y soluciones para la industria Farmacéutica.",


    //MERCADO_FARMACEUTICO_SPRAY_NASAL

    "TITULO_SPRAY_NASAL" => "Spray Nasal",
    "TEXTO_SPRAY_NASAL" => "El mercado de los sprays nasales es una parte importante del sector farmacéutico que aborda una variedad de necesidades de salud relacionadas con el tracto respiratorio superior. Estos productos están diseñados para administrar medicamentos directamente en la cavidad nasal, lo que los hace efectivos para tratar afecciones como congestión nasal, alergias, sinusitis, resfriados y rinitis entre otros.",
    "SUBTITULO_SPRAY_NASAL" => "Algunos de los puntos clave de este mercado son:",
    "LISTA1_SPRAY_NASAL" => "<li>Crecimiento de mercado: El mercado de los sprays nasales ha experimentado un crecimiento constante debido a factores como el aumento de la prevalencia de condiciones respiratorias, el envejecimiento de la población y una mayor conciencia sobre el autocuidado de la salud.</li><li>innovación: Las empresas farmacéuticas están en constantemente innovando en el desarrollo de nuevos productos y formulaciones para mejorar la eficacia, la comodidad y seguridad de los sprays nasales.</li><li>Regulación: Los sprays nasales están sujetos a regulaciones estrictas por parte de las agencias de salud en diferentes países para garantizar su seguridad y eficacia. Esto incluye requisitos de etiquetado claros, pruebas de seguridad y calidad.</li>",
    "SUBTITULO2_SPRAY_NASAL" => "Ingredientes químicos utilizados en los sprays nasales:",
    "LISTA2_SPRAY_NASAL" => "<li>Descongestionantes: Los descongestionantes nasales son a menudo compuestos adrenérgicos, como la oximetazolina, la fenilefrina o la pseudoefedrina. Estos compuestos actúan sobre los receptores alfa- adrenérgicos en los vasos sanguíneos nasales causando construcción y reduciendo la congestión nasal.</li>Antihistamínicos: los antihistamínicos utilizados en los sprays nasales como la azelastina o la olopatadina bloquean los receptores de histamina en la mucosa nasal, lo que ayuda a reducir la inflamación y los síntomas asociados con la rinitis alérgica.<li></li><li>Corticosteroides: Los corticosteroides nasales, como la fluticasona, la budesónida o la mometasona, son potentes antiinflamatorios que reducen la inflamación y la hinchazón de la mucosa nasal al inhibir la liberación de los mediadores inflamatorios y la síntesis de citoquinas.</li><li>Conservantes y estabilizadores: Los conservantes y estabilizadores se utilizan para mantener la esterilidad y la estabilidad del producto durante su vida útil. Estos ingredientes pueden incluir conservantes como el cloruro de benzalconio o el cloruro de sodio, así como estabilizadores de pH y antioxidantes</li>",
    "PRODUCTOS_SPRAY_NASAL" => "Productos",
    "GLICERINA_SPRAY_NASAL" => "Glicerina",
    "TEXTO_GLICERINA_SPRAY_NASAL" => "Ingrediente versátil de alta pureza ideal para aplicaciones industriales, cosméticas y farmacéuticas.",

    //MERCADO_FARMACEUTICO_JARABES

    "TITULO_JARABES" => "Jarabes",
    "TEXTO_JARABES" => "Los jarabes tuvieron su origen entre 1820 – 1896 creados por el farmacéutico francés Abel Guillón.",
    "TEXTO2_JARABES" => "La industria de los jarabes es una parte importante del sector farmacéutico y de salud en general. Estos jarabes también conocidos como soluciones liquidas, son formulaciones liquidas que contienen uno o mas ingredientes activos disueltos en un vehículo líquido, generalmente agua, azúcar u otros aditivos.",
    "SUBTITULO_JARABES" => "Aspectos importantes a considerar sobre la industria:",
    "LISTA1_JARABES" => "<li>Variedad de productos: La industria de los jarabes ofrece una amplia variedad de productos para satisfacer las necesidades del mercado. Esto incluye jarabes simples, como jarabe de maíz y jarabe de azúcar, así como jarabes especializados, como jarabe de arce, jarabe de agave y jarabe de maltitol, que se utilizan en productos específicos o en la formulación de alimentos y bebidas para dietas especiales.</li><li>roducción y formulación: Los jarabes se producen mediante la mezcla de diferentes ingredientes, como azucares (como jarabe de maíz, jarabe de glucosa, jarabe de sacarosa) agua y en ocasiones otros aditivos como saborizantes, colorantes y conservantes.</li><li>Ingredientes y aditivos: Los ingredientes principales de los jarabes son los azucares, que pueden provenir de diversas fuentes como la caña de azúcar, la remolacha, el maíz, el arroz y el trigo y otros cereales. Además de los azucares se pueden agregar otros ingredientes y aditivos para mejorar las características organolépticas.</li>",
    "SUBTITULO2_JARABES" => "Ingredientes químicos mas importantes de los jarabes:",
    "LISTA2_JARABES" => "<li>Agua: El agua es un componente esencial en la mayoría de los jarabes, ya que se utilizan a disolver los ingredientes y ajustar la viscosidad del producto final.</li><li>Ácidos: Algunos jarabes pueden contener ácidos como acido cítrico o ácido málico, que se utilizan para equilibrar el sabor y proporcionar acidez.</li><li>Saborizantes y colorantes: Se pueden agregar saborizantes y colorantes naturales o artificiales para mejorar el sabor y la apariencia del jarabe. Estos pueden incluir extractos de frutas, aromas artificiales y colorantes alimentarios.</li><li>Conservantes: En algunos casos, se pueden agregar conservantes como el benzoato de sodio o el sorbato de potasio para prolongar la vida útil del jarabe al inhibir el crecimiento de microorganismos.</li><li>Espesantes y estabilizantes: Para controlar la viscosidad y estabilidad del jarabe, se pueden agregar espesantes y estabilizantes como la goma guar, la goma xantana y la carragenina.</li><li>Edulcorantes artificiales: En los jarabes diseñados para ser bajos en calorías o sin azúcar, se pueden utilizar edulcorantes artificiales como el aspartamo, la sucralosa o el acesulfamo de potasio para proporcionar dulzor sin agregar calorías.</li>",
    "SUBTITULO3_JARABES" => "Tipos de Jarabes",
    "LISTA3_JARABES" => "<ol><li>Jarabes Aromáticos (Jarabes no medicamentosos<ol><li>Sirven como vehículos de preparación extemporáneas,</li><li>Como punto de partida de jarabes medicamentos,</li><li>Jarabe simple, jarabe de zumos</li></ol></li></ol>",
    "LISTA4_JARABES" => "<ol><li>Jarabes medicamentosos <ol><li>Jarabe Antihistamínico</li></ol></li></ol>"



];